apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${APPLICATION_NAMESPACE}
resources:
  - resources/externalSecret.yaml
  - resources/deployment.yaml
  - resources/service.yaml
#  - resources/virtualService.yaml