spring:
  application:
    name: s3-connection

  r2dbc:
    name: mpft
    url: r2dbc:postgresql://localhost:5432
    username: mpft
    password: mpft
  sql:
    init:
      mode: embedded

server:
  port: 8083
