apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APPLICATION_NAME}-app
  namespace: ${APPLICATION_NAMESPACE}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: ${APPLICATION_NAME}
    kind: SecretStore
  target:
    name: app-secrets
  dataFrom:
  - find:
      path: /${CLUSTER_ENV}/${CLUSTER_NAME}/${APPLICATION_NAME}/
      name:
        regexp: .*
    rewrite:
    - regexp:
        source: "/${CLUSTER_ENV}/${CLUSTER_NAME}/${APPLICATION_NAME}/(.*)"
        target: "$1"
  - find:
      path: /${CLUSTER_ENV}/${CLUSTER_NAME}/shared
      name:
        regexp: .*
    rewrite:
    - regexp:
        source: "/${CLUSTER_ENV}/${CLUSTER_NAME}/shared/(.*)"
        target: "$1"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APPLICATION_NAME}-ssh
  namespace: ${APPLICATION_NAMESPACE}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ${APPLICATION_NAME}
    kind: SecretStore
  target:
    name: ssh-secrets
  dataFrom:
  - find:
      path: /${CLUSTER_ENV}/${CLUSTER_NAME}/${APPLICATION_NAME}/ssh
      name:
        regexp: .*
    rewrite:
    - regexp:
        source: "/${CLUSTER_ENV}/${CLUSTER_NAME}/${APPLICATION_NAME}/ssh/(.*)"
        target: "$1"
  - find:
      path: /${CLUSTER_ENV}/${CLUSTER_NAME}/shared
      name:
        regexp: .*
    rewrite:
    - regexp:
        source: "/${CLUSTER_ENV}/${CLUSTER_NAME}/shared/(.*)"
        target: "$1"
